src/main/kotlin/com/coxautodev/graphql/tools/ResolverDataFetcher.kt, src/test/groovy/com/coxautodev/graphql/tools/ResolverDataFetcherSpec.groovy
Here are the fixes.
Fixed a failure when attempting to find the appropriate resolver for properties on data classes that have a return type of java.lang.Boolean. The java.lang.Boolean is not assignable to kotlin.Boolean::class.java. Kotlin's java platform types map to the primitive types, i.e. 'boolean'. In this case, we now check for 'boolean' as the class name. If there is a better way to do this, I'm not immediately aware. Added a test case to cover the Boolean case.
Another failure occurred when assuming a Boolean|boolean value on a class used the 'is' prefix. This is a Java convention and is not enforced. Kotlin does not generate 'is' properties when declaring Boolean properties as it generates a 'get' prefix on vals/vars. Kotlin Boolean values would therefore fail the method lookup. …
=> Fixed issues when dealing with java Boolean (Object type), and Kotlin Boolean props.

src/main/kotlin/com/coxautodev/graphql/tools/ResolverDataFetcher.kt
Hi,
I ran into an issue with a resolver such as:
public class DataSetResolver  implements GraphQLResolver<DataSet> {
...
}
where I had a number of subclasses of DataSet. I sometimes wanted to work against the generic DataSet and sometime against the more specialized subclasses, as such I had both in the QueryQL schema... The fix below got it working for me.
=> Source class issue

src/main/kotlin/com/coxautodev/graphql/tools/GraphQLSubscriptionResolver.java, src/main/kotlin/com/coxautodev/graphql/tools/RootTypeInfo.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaObjects.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/groovy/com/coxautodev/graphql/tools/Utils.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt
graphql-java has some support for executing subscriptions - the "query" you would run when you want to notify your subscribed clients of some event.
This PR just adds subscription as another supported operation.
The subscribing/unsubscribing, transport, etc. are not handled here, those are perhaps concerns for another library.
The test currently just uses the context to pass data about the event that occurred to the resolver, but maybe there's a better (and more type-safe) way to do this.
=> Add subscription support.

src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt, src/test/groovy/com/coxautodev/graphql/tools/SchemaParserSpec.groovy
This is a regression from fixing ticket #56. There were 2 bugs:
1) The input and output type validation only checked that GraphQL
objects and inputs were used recursively, but didn't account for other
types like enums, interfaces, and unions. This wasn't captured in the
test suite due to #2 below, but this resulted in a SchemaError if you
used optional enums in input types, or used an optional enum, interface,
or union as an output type.
2) The determine(Input/Output)Type logic asserts against the wrapped
GraphQLType, meaning if you had a list (GraphQLList) or required field
(GraphQLNonNull), it didn't perform the new check since the
GraphQLTypeReference was nested. This is why the existing EndToEnd test
suite continued to pass since it marks almost all parameters that have
enums as …
=> Fix input and ouput type checking

src/main/kotlin/com/coxautodev/graphql/tools/TypeClassMatcher.kt
GraphQL list type representation is too limited to be mapped only to java.unit.List. Instead we should be able to represent probably any java Iterable type. As a result I'm getting the error for models with Iterables types other than List:
```
class User {
addresses: Set<Address>
}
type User {
addresses: [Address]
} 
Exception in thread "main" com.coxautodev.graphql.tools.SchemaClassScannerError: 
Unable to match type definition (ListType{type=TypeName{name='Address'}}) with java type (java.util.Set<Address>): 
Java class is not a List: java.util.Set<Address>
```
=> Associate GraphQL ListType with any Iterable in Java

src/main/kotlin/com/coxautodev/graphql/tools/PropertyFieldResolver.kt
MethodFieldResolver already supports null and Optional as the returned values. However, the PropertyFieldResolver does not do the same. Since normally a field should not be declared as Optional, this is the minimal change needed to support null value properly.
=> Support null value in PropertyFieldResolver.

src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt, src/test/groovy/com/coxautodev/graphql/tools/SchemaClassScannerSpec.groovy
There's a problem in the `dictionary.containsKey(type)` check which caused the issue. I wasn't able to reproduce it using tests, but this change finally solved the problem for me.
=>  changed check if dictionary contains interface type (fixes #97)

src/main/kotlin/com/coxautodev/graphql/tools/ResolverInfo.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt
This fixes #99 for spring proxies. Might not be optimal, since the function was turned into a public instead of protected function, but it highlights were the issue was.
=> Fixes #99 for spring proxies.

src/main/kotlin/com/coxautodev/graphql/tools/GuiceAopProxyHandler.java, src/main/kotlin/com/coxautodev/graphql/tools/ResolverInfo.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt
Should fix #107. There might be a better way to detect a guice proxy, but i did not find an equivalent for Spring's AopUtils.
Unit-Tests of this project ran through: https://github.com/kalthas/graphql-guice
=> Fixes #107.

README.md, src/main/kotlin/com/coxautodev/graphql/tools/FieldResolverScanner.kt, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt
A proposal for allowing field resolvers that match method names that are reserved or already exist on `java.lang.Object`, e.g `class`, `hashCode` etc.
=> Support field resolver methods of the format getField<Name>

pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/JavassistProxyHandler.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt
HK2 creates Javassist based proxies when you do AOP, so this is needed to
support them.
Basically a variation of #107
I'm not a Kotlin guy, but I am wondering how the whole class resolving here works? Because I did the same thing as in the `Spring4AopProxyHandler` which has an `import` on `org.springframework.aop.support.AopUtils`. In the Java world that would make the class unloadable in case these dependencies are not there, but apparently for Kotlin that works?
=> Support for Javassist proxies

src/main/kotlin/com/coxautodev/graphql/tools/TypeClassMatcher.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt
Only first argument should be List (this fixes #93)
=> Expect only first parameter as List in Batched

src/main/kotlin/com/coxautodev/graphql/tools/FieldResolverScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt, src/test/groovy/com/coxautodev/graphql/tools/MethodFieldResolverDataFetcherSpec.groovy
Allows the injection of the context as the last argument instead of the environment. Injecting both is not allowed, but it makes no sense anyway, as the context can be retrieved from the environment.
=> Context injection

src/main/kotlin/com/coxautodev/graphql/tools/ResolverInfo.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt, src/test/groovy/com/coxautodev/graphql/tools/SchemaParserSpec.groovy
This resolver adds support for multiple type resolvers related to the
same data type. The `MultiResolverInfo` wraps a list of
`NormalResolverInfo` and checks their data type class. It also overrides
the `getFieldSearches` method to provide a list of `Search` instances
with all resolvers first and a `Search` instance for the data type
class.
`SchemaClassScanner.scanQueueItemForPotentialMatches` now tries to use
`NormalResolverInfo` if there are more then one potential type resolvers
available through the `resolverInfos` field.
=> Add `MultiResolverInfo` implementation

src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt
When parsing the schema and building default values, use List instead of Java array, since graphql-java expects an Iterable value for the list type (see AstValueHelper::handleList)
Fixes issue #92
=> Fix schema introspection bug for arguments of type list

src/main/kotlin/com/coxautodev/graphql/tools/DictionaryTypeResolver.kt
This is an attempt to solve https://github.com/graphql-java/graphql-java-tools/issues/139.
The idea here is, user can register a parent class or an interface in the GraphQL. When the union looks up the corresponding GraphQL type, it would try to resolve the type by the instance type, and then walk up the class hierarchy. If still cannot find any mapped GraphQL type, it would try to look at all implemented interfaces and their mapped GraphQL type.
=> Enhance type mapping in union

pom.xml
With the end of support for java 1.9  it's important to keep project working with currently supported version of jdk which is 10.
Unfortunately, apache.commons.lang 3.6 check java version installed in the system, but due to change 
in the standard of version naming (for java 9 it was "1.9" while for java 10 it's "10") library with version 3.6 fails to resolve "10" as an acceptable version of JVM and thus throws an exception.
In version 3.7 this case was fixed and java 10 is accepted as valid version.
=> Bump apache-commons to add compatibility with Java 10

src/main/kotlin/com/coxautodev/graphql/tools/GenericType.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt, src/test/groovy/com/coxautodev/graphql/tools/TypeClassMatcherSpec.groovy
As noted by @sp00m in https://github.com/graphql-java/graphql-java-tools/pull/120 the PR only solved issue of single-value generics, eg `Mono<T> -> Future<T>`. Flat transformations of list-like generics, eg `Flux<T>`, still had issues due to unwrapping strategy of `GenericType`.
This PR adds `schemaWrapper` parameter which allows flat transformations for generics. Though this PR directly addresses `Flux<T> -> List<T>` transformation it could potentially solve more complex issues for other types as well.
The solution for `Flux<T> -> List<T>` transformation problem using this PR would be to register new `GenericWrapper`
```
SchemaParserOptions.GenericWrapper.listCollectionWithTransformer(
Flux::class.java,
0,
{ flux -> flux.collectList().toFuture() }
)
```
If you check commit …
=> Generic wrapper improvement. Pt. II

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/PerFieldConfiguringObjectMapperProvider.kt, src/main/kotlin/com/coxautodev/graphql/tools/PerFieldObjectMapperProvider.java, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt
- Move the default initialisation of the ObjectMapper behind a provider
- By default still use an ObjectMapperConfigurer  based provider
=> Introduce PerFieldObjectMapperProvider

README.md, src/main/kotlin/com/coxautodev/graphql/tools/FieldResolverScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/PropertyFieldResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/PropertyMapResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt
* Added an additional field resolver and logic to recognize java.util.Map based objects as property maps.
* Fixed issue where presence of a type in the type dictionary did not
allow non-scalar map types to be resolved.
* Updated documentation with respect to how fields are resolved.
=> Issue #113: Support for PropertyDataFetcher behavior

pom.xml
Fixes #195
Upgraded commons-lang3 to 3.8.1, which does not expose such problem.
=> Fixed java.lang.NullPointerException: null while running on Java 11

pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/FieldResolverScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt, src/test/kotlin/com/coxautodev/graphql/tools/MethodFieldResolverDataFetcherTest.kt
=> Kotlin coroutines support

example/pom.xml, example/src/main/java/com/coxautodev/graphql/tools/example/resolvers/Mutation.java, example/src/main/resources/swapi.graphqls, pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt, src/main/kotlin/com/coxautodev/graphql/tools/TypeDefinitionFactory.java, src/main/kotlin/com/coxautodev/graphql/tools/relay/RelayConnectionFactory.kt, src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt, src/test/groovy/com/coxautodev/graphql/tools/RelayConnectionSpec.groovy, src/test/java/com/coxautodev/graphql/tools/ReactiveTest.java, src/test/java/com/coxautodev/graphql/tools/RelayConnectionTest.java, src/test/resources/Reactive.graphqls, src/test/resources/RelayConnection.graphqls
Still a work in progress and a rough implementation thus far, but gives an idea how directives could be supported.
=> Add support for directives

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpec.kt
=> Fix resolving generic properties

pom.xml
Add the test-jar to the maven project, so others can take advantage of some test helpers, like `Util.assertNoGraphQlErrors`.  This is automatically attached to the build, so will be deployed to Maven Central.
=> Add test jar, to be shared with others

src/main/kotlin/com/coxautodev/graphql/tools/relay/RelayConnectionFactory.kt, src/test/java/com/coxautodev/graphql/tools/RelayConnectionTest.java
Right now, `PageInfo` type generated by `RelayConnectionFactory` includes only `hasPreviousPage`/`hasNextPage` fields. While not strictly necessary as per the [core spec](https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo), they are, indeed, already supported by `graphql-java` (https://github.com/graphql-java/graphql-java/blob/v11.0/src/main/java/graphql/relay/PageInfo.java#L17, https://github.com/graphql-java/graphql-java/blob/v11.0/src/test/resources/thingRelaySchema.graphqls#L8) and used in official Relay examples, the only thing necessary was to expose them in schema.
=> added startCursor and endCursor fields to PageInfo graphql type

pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/GenericType.kt, src/main/kotlin/com/coxautodev/graphql/tools/PropertyMapResolver.kt
This PR is a fix for #228. 
As far as I can tell, the `mapClass` getting passed in is never a `ParameterizedType` so `PropertyMapResolver#getMapGenericType` always returns `Object::class.java` (and even if it was generic, the code is looking at the type parameters on the wrong class). This leads to the limitation documented [here](https://www.graphql-java-kickstart.com/tools/schema-definition/):
> Note: If one of the values of a type backed by a java.util.Map is non-scalar then this type will need to be added to the type dictionary (see below).
This PR attempts to fix the issue by using ClassMate to introspect the Map type parameters. This fixes the issue described in #228 and makes map resolvers work without the need to add to the dictionary. 
However, this PR doesn't fix the issue with …
=> Better detection of map type parameters

src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt, src/test/groovy/com/coxautodev/graphql/tools/SuperclassResolverSpec.groovy
=> Add arguments in correct order when building Object

pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/RootTypeInfo.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt, src/main/kotlin/com/coxautodev/graphql/tools/relay/RelayConnectionFactory.kt, src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt, src/test/groovy/com/coxautodev/graphql/tools/MethodFieldResolverDataFetcherSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/MethodFieldResolverDataFetcherTest.kt
These changes migrate graphql-java-tools towards graphql-java 12.0
I have tested the changes on a medium-large schema (containing enums, directives, mutations etc.), and all seems well.
The most problematic change is that the field GraphQLInterfaceType::typeResolver is not accessible anymore (the getter has become package protected and will be removed in future versions of graphql-java). The workaround for now is to use reflection to access it ...
=> Migrate to graphql-java 12.0

pom.xml
I ran into an issue using resolvers with Java 11, and after some debugging I traced the issue to the Apache commons-lang3 library.
This issue only comes up when implementing a `GraphQLResolver` class - root resolvers, etc are fine.
In `ResolverInfo.kt`, the `NormalResolverInfo::findDataClass` method makes a call to `TypeUtils.determineTypeArguments`, which internally hits a NPE - as commons-lang3 3.8 and below improperly create an enum value representing the current Java version.
By upgrading to 3.9 I have had success running my project again.
Thanks, hope this helps!
=> update commons-lang3 version for Java 11 support

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt
Resolves #294 
The issue describes the problem. This simple fix would make the library more consistent with [graphql-java](https://github.com/graphql-java/graphql-java). It would also allow for easy differentiation between absent and `null` arguments.
`null` -> argument was omitted from the query
`Optional.empty()` -> argument was not omitted and it was set to GraphQL `null`
It makes it possible to use GraphQL `null` in mutations for clearing values without using the `environment.containsArgument` workaround.
=> 294 handle optional parameters

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt
Resolves #294 and fixes #310 
@oliemansm I apologize, the previous PR contained an error.
In case the argument was omitted the value was `null` and it was passed to Jackson deserializer. The deserializer converts `null` to `Optional.empty()` thus defeating the purpose of the PR.
This fix instead bypasses Jackson completely when the value is `null` and uses Jackson only if the value was actually provided.
=> 294 handle optional parameters fix

pom.xml
There are several security vulnerabilities in jackson-databind. (see details here)
This PR updates to the latest available version of jackson.
=> Update jackson version due to security vulnerabilities

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/test/kotlin/com/coxautodev/graphql/tools/MethodFieldResolverTest.kt
See #198 
graphql-java already converts scalar types and lists of scalar types
when used as field arguments.
However the MethodFieldResolver basically serialized that object and
deserialized the value to use it as argument value while it's not really
necessary.
The serialization/deserialization also failed when the (Java) type of the
scalar is not easily serializable/deserializable (for example with
private fields)
=> Fixes #198 - Add support for lists of Scalar field arguments that are already coerced

src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt
Do not pass the query, mutation and subscription also in additionalTypes
when constructing the schema. This avoids problems with duplicate types
when transforming the schema.
Fixes #300
=> Improve Schema Transformation

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt
Reverts graphql-java-kickstart/graphql-java-tools#330
=> Revert "Add the TrivialDataFetcher interface to MethodFieldResolver so that i…"

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt
When using a non-nullable scalar as input type
a regression was introduced by the upgrade of jackson.
A jackson exception occurs internally in the MethodFieldResolver
because the correct deserialiser/serialiser cannot be found.
Somehow this was hidden when using earlier versions of jackson
where this just worked anyhow, but due to changes in jackson this
bug is uncovered. The correct way is of course to fix this in
isScalarType to cover non-nullable scalars, and not rely on
functionality in jackson which no longer seems to be supported.
=> Treat non-nullable scalars as scalars

src/main/kotlin/com/coxautodev/graphql/tools/FieldResolverScanner.kt, src/main/kotlin/com/coxautodev/graphql/tools/Utils.kt, src/test/kotlin/com/coxautodev/graphql/tools/MethodFieldResolverTest.kt
I use java proxies to auto generate resolvers.
But the field resolver complain about the missing generic information.
The problem is, that java proxies declares all interface methods but all generic types are erased.
So the scanning ends with an `Unable to match type definition (...) with java type (interface java.lang.Iterable): Java class is not a List or generic type information was lost: interface java.lang.Iterable` error.
=> Ignore proxies when scanning for field resolvers.

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt, src/main/kotlin/com/coxautodev/graphql/tools/Utils.kt
When using suspending resolvers, graphql-java-tools launches coroutines in the global scope, which makes it impossible to structure concurrency properly. More details on why using `GlobalScope` is not recommended: https://medium.com/@elizarov/the-reason-to-avoid-globalscope-835337445abc.
This PR makes the coroutine scope configurable. This is done by having the GraphQL context implement `CoroutineScope`. It is of course completely optional, `GlobalScope` will still be used by default.
Note: this is different from `coroutineContextProvider` in `SchemaParserOptions`, which does not override the scope, and does not allow having a different scope for each request. A concrete use-case for per-request scopes is to ensure all coroutines spawned by any given request are cancelled after at most 1 …
=> Make coroutine scope configurable via context

pom.xml
This fixes #347.
I added the `maven-enforcer-plugin` with the `dependencyConvergence` rule and fixed the resulting dependency errors.
=> Add compile check for dependency convergence and fix resulting errors

pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt
This patch addresses issue #354 . It upgrades graphql-java to version 14, and fixes a compilation problem.
=> Upgrade to graphql-java 14.0

pom.xml, src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/test/groovy/com/coxautodev/graphql/tools/EndToEndSpec.groovy, src/test/kotlin/com/coxautodev/graphql/tools/EndToEndSpecHelper.kt
This is fix for #240, and test for same issue.
When array of non-nullable scalars is input, an error is thrown from Jackson ObjectMapper. The problem then was, NonNullType was ignored by MethodFieldResolver.isScalarType. Changes in #342 handles NonNullType but it doesn't handle NonNullType.type is ListType.
=> Treat array of non-null scalars as scalars

src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt, src/main/kotlin/com/coxautodev/graphql/tools/Utils.kt
From the [Kotlin docs](https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html#children-of-a-coroutine) we read the following _(emphasis added)_:
> When a coroutine is launched in the CoroutineScope of another coroutine, it inherits its context via CoroutineScope.coroutineContext and the Job of the new coroutine becomes a child of the parent coroutine's job. When the parent coroutine is cancelled, all its children are recursively cancelled, too.
>
> **However, when GlobalScope is used to launch a coroutine, there is no parent for the job of the new coroutine. It is therefore not tied to the scope it was launched from and operates independently.**
In order to avoid creating threads that aren't tied to any parent scopes that may exist, `GlobalScope` has been …
=> changed default CoroutineScope to not use GlobalScope to avoid potential cancellation issues and other pitfalls

pom.xml, src/main/kotlin/graphql/kickstart/tools/MethodFieldResolver.kt, src/test/groovy/graphql/kickstart/tools/EndToEndSpec.groovy, src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt
Remove the reflectasm library, which gives warnings on JDK9+ and doesn't seem to be actively maintained anymore. 
For a more in-depth description, see the associated issue: #390
=> Remove reflectasm. Fixes #390

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/test/groovy/graphql/kickstart/tools/EndToEndSpec.groovy, src/test/groovy/graphql/kickstart/tools/SchemaClassScannerSpec.groovy, src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt
Resolves #353
The GraphQL spec allows `extend input`, but the graphql-java-tools library did not handle this case.
This commit, enables the following to work:
```
type Mutation {
save(input: UserInput!): Boolean
}
input UserInput {
name: String                        
}
extend input UserInput {
password: String
}
```
=> Handle `extended input`

src/main/kotlin/graphql/kickstart/tools/MethodFieldResolver.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt, src/test/kotlin/graphql/kickstart/tools/MethodFieldResolverTest.kt
Resolves #388
Changes the default behavior of `Optional` mapping when used as an input parameter.
This is an adjustment to my previous PR on this topic https://github.com/graphql-java-kickstart/graphql-java-tools/pull/310.
Both options are now supported and the behavior is configurable via the boolean switch `inputArgumentOptionalDetectOmission`:
- when `true` an omitted GraphQL argument during query is converted to `null` and an explicit GraphQL `null` is converted to `Optional.empty()` (https://github.com/graphql-java-kickstart/graphql-java-tools/pull/310)
- when `false` both an omitted GraphQL argument and explicit `null` is converted to `Optional.empty()`; therefore the value is never `null`; **this is the new default!**
I am choosing to make this a breaking change and make the second …
=> 388 fix optional argument handling

pom.xml, src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt, src/test/groovy/graphql/kickstart/tools/SchemaParserSpec.groovy
Fixes #378
Replaced deprecated CoroutineScope.publish(...) with top-level publish(...) method in SchemaParserOptions(See: https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/kotlinx-coroutines-reactive/src/Publish.kt). No new tests were added but existing ones looked sufficient to me. I noticed that @oliemansm didn't upgrade the kotlin-coroutines lib in the "upgrade-dependencies" branch (See: commit 4543ccd) so there might be a reason to not do this update that I am not aware of?!
=> Upgrade kotlin and kotlin-coroutines to versions 1.3.72 and 1.3.9

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt, src/test/groovy/graphql/kickstart/tools/SchemaClassScannerSpec.groovy, src/test/groovy/graphql/kickstart/tools/TestInterfaces.groovy
Resolves #442
Resolves #420 
Adding a new `includeUnusedTypes` option to include add unused types to the final executable schema. The caveat is that the unused types need to be included in the schema parser dictionary. I think it is an ok tradeoff as this feature has specific use cases as described in #420 and #442.
Added a couple of test cases to it as well as serve as both test and example of how to use it.
=> feat: Add option to allow unused types

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/test/groovy/graphql/kickstart/tools/NestedInputTypesSpec.groovy
Fields declared in extension would not be parsed, this PR fixes that issue with corresponding UT.
=> Allowing nested inputs defined in extensions to be parsed as well

src/main/kotlin/graphql/kickstart/tools/relay/RelayConnectionFactory.kt, src/test/kotlin/graphql/kickstart/tools/relay/RelayConnectionFactoryTest.kt
Prevent `RelayConnectionFactory` to do extra work and add new definition when not needed.
=> Prevent to add PageInfo definition if not needed

src/main/kotlin/graphql/kickstart/tools/TypeClassMatcher.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndTest.kt
Resolves https://spectrum.chat/graphql-java-kick/tools/list-of-datafetcherresults~9ca373af-c480-4ae5-869a-775ca8f1885e
graphql-java supports lists of DataFetcherResult.
This PR remove error when DataFetcherResult is not the root return type
=> Remove error when DataFetcherResult is not the root type

.github/workflows/release.yml, .github/workflows/snapshot.yml, github-build.sh, pom.xml
Following the closure of bintray we need to replace it with direct deployment to maven central. 
Unfortunately, following the rest of the org's gradle based config doesn't seem possible. 
However, according to [this guide](https://central.sonatype.org/publish/publish-maven) and [the documentation here](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven) this should work.
=> Remove bintray and deploy to maven central

renovate.json
Adopt a [centralized repository](https://github.com/graphql-java-kickstart/renovate-config) to share common renovate configurations across all kickstart projects
Other projects already migrated
=> Switching to use shareable renovate presets

src/main/kotlin/graphql/kickstart/tools/DictionaryTypeResolver.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndTest.kt
Fixes #558
DictionaryTypeResolver now considers the full type hierarchy -- superinterfaces in addition to superclasses.
=> Test case and proposed fix for #558

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt, src/main/kotlin/graphql/kickstart/tools/util/Utils.kt, src/test/kotlin/graphql/kickstart/tools/SchemaParserTest.kt
The existing behavior is to always fallback to comments from the schema. This change would add a configuration option to `SchemaParserOptions` that would make it possible to ignore comments and exclusively use descriptions from the schema.
For example:
```graphql
type Query {
hello: String!
}
```
This schema with the current behavior would result in the description being `Copyright 2020\nAuthors: ...`.
With the `commentsAsFallbackDescription` option set as false, the description will be null.
=> Add an option to fallback to comments if a description is not provided

src/main/kotlin/graphql/kickstart/tools/resolver/FieldResolverScanner.kt, src/main/kotlin/graphql/kickstart/tools/util/Utils.kt, src/test/kotlin/graphql/kickstart/tools/FieldResolverScannerTest.kt
capitalize() without Locale.ENGLISH leads to unexpected chars which are language specific
=> Make compatible with other JVM Locales

src/main/kotlin/graphql/kickstart/tools/DictionaryTypeResolver.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndTest.kt
Fixes #592
The DictionaryResolverType was returning GraphQL Schema Objects from a cache, however if the shema is transformed by SchemaTransformer, these GraphQL Schema Objects instances can change.
As such we should resolve the GraphQLObjectType from the schema object rather than a local cache.
=> DictionaryResolverType should use return GraphQLObjectType from Schema rather than cached map

src/main/kotlin/graphql/kickstart/tools/RootTypeInfo.kt, src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/main/kotlin/graphql/kickstart/tools/SchemaObjects.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/test/kotlin/graphql/kickstart/tools/SchemaParserTest.kt
Resolves #595
Set description in `GraphQLSchema` object instantiated in `SchemaObjects.toSchema`
=> Schema introspection description

src/main/kotlin/graphql/kickstart/tools/TypeClassMatcher.kt
Add slightly more context to an error message.
=> Add potentialMatch.reference to error message in TypeClassMatcher

src/main/kotlin/graphql/kickstart/tools/directive/DirectiveWiringHelper.kt, src/main/kotlin/graphql/kickstart/tools/directive/SchemaDirectiveWiringEnvironmentImpl.kt
Updating the environment to align with changes made in https://github.com/graphql-java/graphql-java/pull/2834
=> Update directive wiring environment

src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/test/kotlin/graphql/kickstart/tools/DeprecatedDirectiveTest.kt
This pull request adds support for the `@deprecated` directive on arguments and input fields.
Support for this was added in version 17.0 of `graphql-java`.
Fairly simple changes - I added support for this to the main `SchemaParser` class, and added tests for the new and previously-existing functionality.
=> Support @deprecated on arguments and input fields

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt
This PR simply removes an extra `throw` keyword where I don't think it should be.
=> Remove double throw

src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/main/kotlin/graphql/kickstart/tools/directive/DirectiveWiringHelper.kt, src/test/kotlin/graphql/kickstart/tools/DirectiveTest.kt, src/test/kotlin/graphql/kickstart/tools/SchemaClassScannerTest.kt
Fixes #695
- adding back creation of deprecated directives
=> Bugfix/695 - Old-style directives get lost

src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt, src/main/kotlin/graphql/kickstart/tools/resolver/FieldResolverScanner.kt, src/main/kotlin/graphql/kickstart/tools/resolver/MissingFieldResolver.kt, src/main/kotlin/graphql/kickstart/tools/resolver/MissingResolverDataFetcherProvider.kt, src/test/kotlin/graphql/kickstart/tools/MissingFieldResolverTest.kt
Provider for creating missing resolver data fetcher to provide options and field definition to factory
Resolves #741
Allow missing field resolver data fetcher usage a hook to the field definition and options. Moves away from provide a concrete data fetcher implementation and provide a functional interface (aka Provider) when creating the missing resolver data fetchers and pass the field definition and schema parser options for context.
=> Provider for creating missing resolver data fetcher to provide options and field definition to factory

src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt, src/main/kotlin/graphql/kickstart/tools/resolver/FieldResolverScanner.kt, src/test/kotlin/graphql/kickstart/tools/SchemaParserTest.kt
Fixes #334
- added a check during schema parsing to validate that subscription data resolvers return `Publisher` as expected.
=> Validate subscription data resolver during schema parsing

src/main/kotlin/graphql/kickstart/tools/resolver/MethodFieldResolver.kt, src/test/kotlin/graphql/kickstart/tools/MethodFieldResolverTest.kt
Fixes #477 and #713
Removed usage of UndeclaredThrowableException, re-throwing original exception instead
=> Remove usage of UndeclaredThrowableException

pom.xml, src/main/kotlin/module-info.java
This should fix deployment issue with javadoc plugin complaining about an unnamed module.
=> Upgrade to Java 11

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/main/kotlin/graphql/kickstart/tools/TypeClassMatcher.kt, src/main/kotlin/graphql/kickstart/tools/directive/DirectiveWiringHelper.kt, src/test/kotlin/graphql/kickstart/tools/InaccessibleFieldResolverTest.kt, src/test/kotlin/graphql/kickstart/tools/SchemaClassScannerTest.kt
Partially Resolves #664
Scan directives while parsing the schema. This handles any scalar arguments. (Still no support for input objects)
=> Scan directives while parsing schema

src/main/kotlin/graphql/kickstart/tools/SchemaClassScanner.kt, src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt, src/test/kotlin/graphql/kickstart/tools/SchemaClassScannerDirectiveTest.kt, src/test/kotlin/graphql/kickstart/tools/SchemaClassScannerTest.kt
Resolves #664
Added enum and input object type handling to directives. It should be possible to parse any combination of valid GraphQL directives and arguments now.
=> Scan directives arguments while parsing schema

pom.xml, src/main/kotlin/graphql/kickstart/tools/resolver/FieldResolver.kt, src/main/kotlin/graphql/kickstart/tools/resolver/MapFieldResolver.kt, src/main/kotlin/graphql/kickstart/tools/resolver/MethodFieldResolver.kt, src/main/kotlin/graphql/kickstart/tools/resolver/PropertyFieldResolver.kt, src/main/kotlin/graphql/kickstart/tools/util/Utils.kt, src/test/kotlin/graphql/kickstart/tools/DirectiveTest.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt, src/test/kotlin/graphql/kickstart/tools/MethodFieldResolverDataFetcherTest.kt, src/test/kotlin/graphql/kickstart/tools/TestUtils.kt, src/test/kotlin/graphql/kickstart/tools/util/UtilsTest.kt
=> Upgrade graphql-java to 22.3

src/main/kotlin/graphql/kickstart/tools/resolver/FieldResolverScanner.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndSpecHelper.kt, src/test/kotlin/graphql/kickstart/tools/EndToEndTest.kt, src/test/kotlin/graphql/kickstart/tools/SchemaParserTest.kt
Fix oversight from https://github.com/graphql-java-kickstart/graphql-java-tools/pull/756. Allow subscription data resolvers to also return a `CompletableFuture<Publisher>`.
=> Allow future return type for subscription data fetcher
